### PR TITLE
Merge vendor branch with upstream/master

### PR DESCRIPTION
**Pull request by gknopf-spideroak**

### CODE REVIEW

**Comment by gknopf-spideroak** [comment]
Just need someone to verify that the correct commits were pulled in from upstream/master and the merge was done correctly.
No need to review all the changes.

**Comment by chip-so** [comment]
I can confirm that the correct commits are there. I'm going to make sure it actually can build things before I approve.

**Comment by gknopf-spideroak** [comment]
> I can confirm that the correct commits are there. I'm going to make sure it actually can build things before I approve.

That would be a cool thing to automate with github ci.

**Review by chip-so — APPROVED** [review]
Tested with both iOS and Android builds. Seems to work fine. 👍

**Comment by gknopf-spideroak** [comment]
> Tested with both iOS and Android builds. Seems to work fine. 👍

Thanks Chip!

**Comment by chip-so** [comment]
Oh, and I did it without patching any NDK paths, so this appears to solve that issue as well.

**Pull request merged**
